#!/usr/bin/env python
import gevent.monkey
gevent.monkey.patch_all()

import sys
import time
import logging

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s %(levelname)-5.5s [%(name)s-%(process)s] %(message)s')
logging.Formatter.converter=time.gmtime

from zarkov import config
options, args = config.configure(sys.argv)

from zarkov import command
from zarkov import exceptions as exc

try:
    if len(args) > 1:
        Command = command.Command.lookup(args[1])
        command = Command(options, *args[2:])
    else:
        Command = command.Command.lookup('shell')
        command = Command(options)
    if options.profile:
        import cProfile
        cProfile.run('command.run()', options.profile)
    else:
        command.run()
except exc.CommandError, err:
    print err




